name: Sync files to S3

on:
  push:
    branches:
      - protofire

jobs:
  sync-to-s3:
    runs-on: w3-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Sync files to S3 bucket
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./assets   "s3://${S3_BUCKET_NAME}/assets"   --delete
          aws s3 sync ./networks "s3://${S3_BUCKET_NAME}/networks" --delete
